src/fni/fni/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fni_page.urls'))

]

src/fni/fni_page/urls.py
from django.urls import path
from . import views
#from django.conf.urls import url    
from django.urls import re_path as url

app_name = 'fni_page'

urlpatterns = [
    path('', views.home, name="home"),
    path('inflation', views.inflation, name = "inflation"),  
    path('about', views.about, name = "about"), 
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    path('insert_trend_data', views.insert_trend_data, name='insert_trend_data'),
]

src/fni/fni_page/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

# query results and value. 
class Trend(models.Model):
    query_res = models.CharField(max_length=200)
    value = models.CharField(max_length=200, null=True)
    data_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.query_res # render Hello on the admin page Under Treend. 

class User_profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    occupation_and_monthly_saving =models.TextField(blank=True)
    def __str__(self):
        return self.user.username

src/fni/fni_page/forms.py
from django import forms 
from fni_page.models import User_profile
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')
        widgets = {
            'username':forms.TextInput(attrs={'class':'form-control','placeholder': 'Enter your username'}),
            'password':forms.PasswordInput(attrs={'class':'form-control'}),
            'email':forms.TextInput(attrs={'class':'form-control'}),
        }

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = User_profile 
        fields = ('occupation_and_monthly_saving',)
        widgets = {
            'occupation_and_monthly_saving':forms.Textarea(attrs={'class':'form-control'}),

        }

src/fni/fni_page/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .models import * 
from .forms import * 
from pytrends.request import TrendReq
from datetime import datetime, timedelta

def home(request):
	return render(request, 'fni_page/home.html')

@login_required(login_url='/user_login')
def inflation(request):
    trends = Trend.objects.order_by('-data_created')[:5]
    return render(request, 'fni_page/inflation.html', {'trend_list': trends})

def about(request):
	return render(request, 'fni_page/about.html')

def insert_trend_data(request):
    pytrend = TrendReq()
    today_date = str(datetime.now().date())
    ystd = str((datetime.today() - timedelta(days=30)).date())
    pytrend.build_payload(kw_list=['Inflation'],timeframe=f'{ystd} {today_date}')
    related_queries = pytrend.related_queries()['Inflation']['top'].head()
    for i,row in related_queries.iterrows():
        data_ = Trend(query_res=row['query'], value=row['value'])
        data_.save()
    return HttpResponseRedirect('/inflation')


# Login views: 
def index(request):
    return render(request, 'fni_page/home.html')

@login_required
def special(request):
    all_users = User_profile.objects.select_related('user')
    return HttpResponse(all_users[0].occupation_and_monthly_saving)

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('/home'))

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user=user
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else: # if GET request
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    
    return render(request,'fni_page/registration.html',
    {'user_form':user_form,
    'profile_form':profile_form,
    'registered':registered}
    )

def user_login(request):
    if request.method == 'POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/inflation')
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request,'fni_page/login.html')

src/fni/fni_page/templates/fni_page/about.html
{%  extends 'fni_page/main.html' %}

{% block content %}
<!DOCTYPE html>

    <body >
        <section id="about">
            <div class="container px-4">
                <div class="row gx-4 justify-content-center">
                    <div class="col-lg-8">
                        <h2>About FNI project</h2>
                        <p class="lead ">Inflation has been a global issue lately, though it is part of the economical cycle. The drastic increased in Consumer Price Index (CPI) has caused economical stress to the global citizens. This project aims to look into overall market sentiment by scrapping tweets from Twitter, and also the trend and topics of interest by looking into Google Trend. Lastly, these data are also compared to CPI data, to have a better understanding of how people react to inflation and their interest or curiousity surrounding the topic of inflation.  </p>
                        <p class="lead">This is a study project done by Jiong Jiet and Iqram. </p>
                        <p class="lead"> NLP python tools and Django web framework are the main stacks of this project.</p>

                    </div>
                </div>
            </div>
        </section>

       
    </body>

{% endblock %}

src/fni/fni_page/templates/fni_page/home.html
{%  extends 'fni_page/main.html' %}
{% load static %}
{% block content %}



<div class="container px-4">
    <h1>Inflation in depth analysis.</h1>
    <p>Inflation is a general increase in the level of prices in economy.
        This can be caused by several factors. Reduced in supply of goods and services or increase in demand can also lead to inflation. Recently, due to global events (pandemic, geo-political issues, climate crises adn increasing global tension), governments across the world has taken different approaches and their policies in managing the money supply, both by direct government action and the lending of private organizations and individuals, can impact the market and lead to inflation. For instance, the continuous money printing can lead to increase of money circulation in the market, over-printing is a concerning issue as it would lead to hyperinflation, the more you print the less value it holds. </p>
        
        <img class = "rounded mx-auto d-block pt-4" src="{% static 'images/inflation.png' %}" alt="some text">
        
        <p class="pt-3">Though it sounds concerning but inflation is just part of the economical cycle, the real concern here is hyperinflation. Let's look into Consumer Price Index data below and let the stats speak for itself. </p>
        <img class = "col-12" src="{% static 'images/inflation_data.png' %}" alt="some text">
        source: imf.org

        <img class = "col-8  d-block mx-auto"  src="{% static 'images/average_inflation-2021.png' %}" alt="some text">


        <p>Indeed, inflation has been increasing across the year 2021, hyperinflation is a serious issue and could affect global citizens. Next, we look into how general sentiment on Twitter reflect on this actual data.</p>
        

    <img class = " col-8 rounded mx-auto d-block" src="{% static 'images/average_sentiment-2021.png' %}" alt="some text">

    <p>From the sentiment analysis of the total of over 500 tweets in the same year of 2021, we can also see the decline of sentiment throughout the year. Though the chart does not have the same exact pattern as the CPI data, but it shows a trend of negative segment near the end of 2021. This could potentially show that people are suffering eocnomically and expressing their negativity.</p>
    
    <h3>Topic modelling</h3>
    <p>
    Based on the data collected, we have built topic model using LDA. This helps us understand better the discussion and centrral topics surrounding inflation. </p>

    <img class = " col-8 rounded mx-auto d-block" src="{% static 'images/topic-modelling.png' %}" alt="some text">
        <p class="pt-3">The first topic (represents by the big circle with 1), we will name this topic as Politic. The politic topic contains keywords like Biden, control, house, border, job, policy, problem and issue. Which could potentially indicate netizen's dissastisfaction and attributing the cause of inflation to mismanage of government. </p>

        <p>
        The second topic aka the Economic topic, contains keyword such as economic, invest, saving, cash, future and currency. This topic is more technical and discuss more about the solution or ways to mitigate/cope rather than finding out the reasons and finger pointing. </p>

        <p>
        The third topic is the Global topic. This topic have the following keywords: vietnam, pandemic, dollar, debt, world, history, rate, bill, change. This is relevant to the global issues such as Covid/ pandemic which has a global economical impact. </p>

        <p>In conclusion, we can sum up the section of topic modelling with three major topics: Global, economical and political.Though, the model is not the best as political keywords are common among almost all the topics. For future improvment, the model can be trained with different number of topics, tuning the parameters and adjusting the saliency/ reliancy can also improve the model and give better segregation of topics.</p>
</div>




{% endblock %}

src/fni/fni_page/templates/fni_page/inflation.html
{%  extends 'fni_page/main.html' %}
{% load static %}
{% block content %}



<div class="container px-4">
    <h1>Inflation Google Trend</h1>
    
    <div class="col-lg-8"></div>
    <a class="btn btn-primary" href="{% url 'fni_page:insert_trend_data'%}">Refresh data</a>
    <div class="card card-body pt-6">
        <table class="taable pt-6">
            <tr>    
                <th>Trend</th>
                <th>Value </th>
            </tr>
            <tr>
                <td colspan="3"><hr/></td>
            </tr>
            {% for i in trend_list %}
                <tr>
                    <td>{{i.query_res}}</td>
                    <td>{{i.value}}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <p class="pt-3">*Click on refresh button above to get past 30 days (from today) relevant search terms about inflation. </p>
    <p>Data above is based on Google trend, this will query Google api that shows what people are searching about reagarding inflation. We will be able to understand more about what people are thinking about inflation.</p>
    <img height="400" height="400" class = " pt-4 rounded mx-auto d-block"  src="{% static 'images/inflation-meme.jpeg' %}" alt="some text">
</div>




{% endblock %}

src/fni/fni_page/templates/fni_page/login.html
{%  extends 'fni_page/main.html' %}
{% load static %}
{% block content %}

  <div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1>
<form method="post" action="{% url 'fni_page:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
          <label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
            <input type="submit" name="" value="Login">
</form>
</div>
  </div>
{% endblock %}

src/fni/fni_page/templates/fni_page/main.html
{% load static %}
  
<!DOCTYPE html>
<html>
<head>
	<title>CRM</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type= "text/css" href="{% static '/css/main.css' %}">
</head>
<body>
	{%  include 'fni_page/navbar.html' %}
	<div class="container-fluid">
	{% block content %}



	{% endblock %}
    </div>
	<hr>
	<!-- <h5>Our footer</h5> -->
	
</body>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

src/fni/fni_page/templates/fni_page/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">FNI Project</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="/inflation">Inflation_FNI</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="/about">About this project</a>
        </li>
      </ul>

      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/register">Register</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="/user_login">Login</a>
        </li>
      </ul>

    </div>
  </nav>

src/fni/fni_page/templates/fni_page/registration.html
{%  extends 'fni_page/main.html' %}
{% load static %}
{% block content %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Hello there, you are registered.</h1>
        Proceed to the login page <a class="nav-link" href="/user_login">here</a>.
      {% else %}
        <h1>Registration form</h1>
        <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" name="" value="Register">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}